"""officergang relationship

Revision ID: 2cd2150964ed
Revises: d4f84843a8b7
Create Date: 2024-09-30 21:01:44.983608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cd2150964ed'
down_revision = 'd4f84843a8b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shooting', schema=None) as batch_op:
        batch_op.alter_column('lat',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=8),
               existing_nullable=True)
        batch_op.alter_column('lng',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=8),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shooting', schema=None) as batch_op:
        batch_op.alter_column('lng',
               existing_type=sa.Float(precision=8),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('lat',
               existing_type=sa.Float(precision=8),
               type_=sa.REAL(),
               existing_nullable=True)

    # ### end Alembic commands ###
