"""officergang association table

Revision ID: 866ea1e54164
Revises: b31bd18f1bb2
Create Date: 2024-09-23 17:37:10.767237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '866ea1e54164'
down_revision = 'b31bd18f1bb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('officergang',
    sa.Column('officer', sa.String(length=64), nullable=True),
    sa.Column('gang', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gang'], ['gang.name'], ),
    sa.ForeignKeyConstraint(['officer'], ['gangmember.officer'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('gangmember', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['officer'])

    with op.batch_alter_table('shooting', schema=None) as batch_op:
        batch_op.alter_column('lat',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=8),
               existing_nullable=True)
        batch_op.alter_column('lng',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=8),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['victim'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shooting', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('lng',
               existing_type=sa.Float(precision=8),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('lat',
               existing_type=sa.Float(precision=8),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('gangmember', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('officergang')
    # ### end Alembic commands ###
