"""initial migration

Revision ID: b31bd18f1bb2
Revises: 
Create Date: 2024-09-23 17:33:55.543061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b31bd18f1bb2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('gang',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('gangmember',
    sa.Column('badge', sa.Integer(), nullable=True),
    sa.Column('officer', sa.String(length=64), nullable=False),
    sa.Column('bio', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('officer'),
    sa.UniqueConstraint('badge'),
    sa.UniqueConstraint('officer')
    )
    op.create_table('shooting',
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('victim', sa.String(length=64), nullable=False),
    sa.Column('officer', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('lat', sa.Float(precision=8), nullable=True),
    sa.Column('lng', sa.Float(precision=8), nullable=True),
    sa.Column('weapon', sa.String(length=128), nullable=True),
    sa.Column('outcome', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('victim'),
    sa.UniqueConstraint('victim')
    )
    op.create_table('officercase',
    sa.Column('officer', sa.String(length=64), nullable=True),
    sa.Column('case', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['case'], ['case.id'], ),
    sa.ForeignKeyConstraint(['officer'], ['gangmember.officer'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('officercase')
    op.drop_table('shooting')
    op.drop_table('gangmember')
    op.drop_table('gang')
    op.drop_table('case')
    # ### end Alembic commands ###
